[project]
name = "lotus"
version = "0.0.1"
description = "A lightweight JAX reinforcement learning library"
authors = [
    {name = "Alex Goddard"},
]
dependencies = [
    "numpy>=2.0.0",
    "jax>=0.7.0",
    "flax>=0.11.0",
    "chex>=0.1.90",
    "optax==0.2.5",
    "distrax==0.1.5",
    "gymnax==0.0.9",
]
requires-python = ">=3.10"
readme = "readme.md"
license = {text = "Apache-2.0"}

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[tool.pdm]
distribution = true